### PR TITLE
Implement hello-world exercise

### PR DESCRIPTION
**Pull request by marcCanipel**
I'll work on the hello world exercise
https://github.com/exercism/x-common/tree/master/exercises/hello-world

### CODE REVIEW

**Comment by kytrinyx** [comment]
@marcCanipel I'm sorry it has taken me three months to see this!

Would it be possible to update the exercise so that it doesn't use any HTML?

**Comment by bdw429s** [comment]
Just curious, are the files in this pull supposed to be valid CFML?  They are in `.cfc` files which is used to denote a class (or component as we call it) in CFML.  Yet the only valid contents of a file with that extension would be `component { ... }`.  You'd generally only template HTML in a .cfm file.

**Comment by kytrinyx** [comment]
@bdw429s Thanks—yeah, I would expect this to be a component, not template HTML.

**Comment by bdw429s** [comment]
I implemented the hello world exercise as part of this pull.  
https://github.com/exercism/coldfusion/pull/26

If that is fine, and pull 26 gets merged, this pull can be closed/canceled.

**Comment by kytrinyx** [comment]
That sounds great @bdw429s. Thank you!

**Pull request closed without merging**
