### PR TITLE
Add default introductory code example

### PR DESCRIPTION
**Pull request by kytrinyx**
Instead of having logic for a fallback in the backend, we're choosing a
default for the snippet file.

For tracks that have core exercises, we pick the first core exercise.
For tracks without these, we pick the first exercise listed in the config.

Note that we're aiming for 10 lines and a max-width of 40 columns.
This solution has 11 lines and a max-width of 48, so we may want to adjust it.

See https://github.com/exercism/meta/issues/89

### CODE REVIEW

**Comment by kytrinyx** [comment]
I think we'd be better off with a more classic "Hello World" here, to be honest. Meh. If someone else would submit a hello world snippet, I'd love to accept that instead of merging this.

**Comment by bdw429s** [comment]
Saw the tweet that linked to here, but unsure of what you actually are looking for.  I'm sure that code sample could easily be whittled down to 10x40.  Just remove some white space, less tabbing and brevity like `&&` instead of `AND`.
But what exactly are you looking for? Does it need to be a class?  Follow a certain interface?  Do something specific?  Where is this code sample being used?

**Comment by kytrinyx** [comment]
@bdw429s Thanks so much! Yeah, I clearly forgot a bit of context.

We would be using this on the homepage of the ColdFusion track in the new Exercism site (if it ever gains enough traction to get launched... I'm realizing this might not be realistic in the near term).

Here's the Go track:

https://v2.exercism.io/tracks/go

What we're aiming for is something that just gives a taste of what the language looks like. It doesn't have to be sophisticated in any way, it's just the first glance as part of an intro that is hoping to entice people in to try the language.

I've been updating all the language tracks, both the active ones and the ones where the people who started it have not stuck around.

Having thought about it, though... the right answer here might just be to archive this track and revive it if someone comes along and wants to put in a chunk of effort to launch the track properly.

Thanks so much for taking the time to ask.

**Comment by bdw429s** [comment]
Taking the Go example, here would be the equivalent CFML:

```js
component {

  // helloWorld greets the world.
  function helloWorld() {
    return 'Hello, World!';
  }

}
```

It sounds like it would be cool to have CFML be represented here.  I can try to help contribute but the biggest issue you'll find is there isn't a metric ton of CFML devs who will contribute since we have a smaller community.  

Does this site deal with actually helping people run the code or having runnable examples, or does it assume the user already has a working knowledge of the language and has local development set up.  I can definitely help with guiding people to run code.  I maintain a project called CommandBox CLI which is a tool for CFML devs to use a REPL, do commandline execution of CFML/shebang scripts, and start ad-hoc servers.  There could be some simple conventions for being able to clone the code and run `box start` or something similar to run it with predefined settings.

**Comment by kytrinyx** [comment]
> you'll find is there isn't a metric ton of CFML devs who will contribute since we have a smaller community.

Yeah, I thought that might be the case.

> Does this site deal with actually helping people run the code or having runnable examples, or does it assume the user already has a working knowledge of the language and has local development set up. 

The goal is to guide them in setting everything up: https://github.com/exercism/docs/blob/master/language-tracks/documentation/for-consumers.md
and once set up, the tests that we deliver should be runnable, but failing.

The site simulates TDD by providing a pre-written test suite, which helps people get bootstrapped into writing code really quickly.

For some languages setup is straight forward, others... kind of nightmarish. It's always exciting to see where a new track falls.

> I maintain a project called CommandBox CLI 

Ah, cool! That could be handy.

Our goal is for people to be up and running in the smoothest, least painful way possible, so that they can get their first tests passing as quickly as possible, while still sticking with the most vanilla setup feasible. Sometimes vanilla is just too painful, though, or there really is no way to do it (MIPS Assembly, for example, needs to run in an emulator).

So there's a whole lot of stuff we can discuss to figure out what the best setup is for a track, and I'm always happy to chat about these things. If you do decide that you want to jump in, let's move this conversation into https://github.com/exercism/coldfusion/issues/1

To see if this is something you'd be interested in playing with, the best two places to start reading are probably the track basics and the high-level maintainer docs:
- https://github.com/exercism/docs/tree/master/language-tracks
- https://github.com/exercism/docs/blob/master/maintaining-a-track/README.md

If you've never heard of Exercism before there might be some high-level context missing (I'm still trying to figure out how to organize everything to make sense).

Also, the track maintainer docs are a bit in flux since we're in the middle of trying to get the new site launched (https://github.com/exercism/v2-feedback/blob/master/README.md), so if you decide to jump in and discover that it's not making sense, just holler—I'll try to both explain and fix the docs.

We have a ton of exercises that maintainers can cherry-pick from when starting up a new track. Some exercises won't be a good fit for the language, others might need tweaking, but a lot of it can be ported in a pretty straight-forward way from the suggested (a.k.a. "canonical") test inputs and outputs. The list of unimplemented exercises is here: http://exercism.io/languages/coldfusion/todo and the docs are in the Exercism docs repo.

**Comment by bdw429s** [comment]
Thanks for the reply.  I moved the conversation over to https://github.com/exercism/coldfusion/issues/1

**Comment by bdw429s** [comment]
I added my default introductory code sample above into the files I'm submitting in this pull:
https://github.com/exercism/coldfusion/pull/26

If that is fine, and pull 26 gets merged, this pull can be closed/canceled.

**Comment by kytrinyx** [comment]
That's perfect. Thank you!

**Pull request closed without merging**
